### ISSUE TITLE
Not blocking private IP on DNS request

### ISSUE THREAD

**Issue by ManoloTech** [4390c336/stopdnsrebind#37]
I re-compiled CoreDNS with this pluing, I am configuring it on the Corefile but is not preventing DNS responses with public IPs. 

Tried with the example syntax, and some others, e.g.:

```
.:53 {
    cache 30
    forward . 8.8.8.8 1.1.1.1
    log
    errors
    stopdnsrebind .
}
```

What am I missing?

**Comment by 4390c336** [comment]
Hi @ManoloTech ,
the order inside `plugin.cfg` matters, 
so you can try and add the plugin after for example `acl:acl` and try again.
